version: "2"
services:
  app:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - "/dev:/mnt/host/dev"
      - "/etc:/mnt/host/etc"
      - "/etc/os-release:/mnt/host/etc/os-release"
      - "/proc:/mnt/host/proc"
      - "/sys:/mnt/host/sys"
